# Generated by Django 2.2.6 on 2019-12-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Blogpost',
        ),
    ]
