# Generated by Django 2.2.6 on 2019-12-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='number',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
